"""change cost_usd from float to numeric(12,6)

Revision ID: a3c2d266f101
Revises: ae7ecabcf79d
Create Date: 2026-03-11 03:03:51.677214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c2d266f101'
down_revision: Union[str, Sequence[str], None] = 'ae7ecabcf79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_logs', 'cost_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=False)
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    op.alter_column('usage_logs', 'cost_usd',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
